# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
