# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0002_auto_20170422_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_registration_app.User'),
        ),
    ]
